apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smart-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: service
                port:
                  number: 9080