apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{project-name}}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /apimodule(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: apimodule-service
                port:
                  number: 9080